import { RiPhoneFill } from "react-icons/ri";
import { FiBox } from "react-icons/fi";
import { TiCancel } from "react-icons/ti";
import { IoIosArrowForward } from "react-icons/io";
import { SiBrandfolder } from "react-icons/si";
import { BsCart } from "react-icons/bs";
import { GoDotFill } from "react-icons/go";
import { BiSolidLogOut } from "react-icons/bi";
import { LuSun, LuArrowLeftToLine } from "react-icons/lu";
import { FaXmark } from "react-icons/fa6";
import {
  IoCartOutline,
  IoLogOutOutline,
  IoReaderOutline,
  IoPersonOutline,
  IoNotificationsOutline,
  IoMoonOutline,
  IoSunnyOutline,
  IoTimeOutline,
  IoBarChartOutline,
  IoPeopleOutline,
  IoCreateOutline,
  IoFootballOutline,
  IoLogoBuffer,
  IoPricetagOutline,
  IoNewspaperOutline,
  IoChatbubblesOutline,
  IoTicketOutline,
  IoReturnUpBackOutline,
  IoPlaySkipBackOutline,
  IoLogInOutline,
  IoBarChart,
  IoPhonePortrait,
  IoHome,
  IoMail,
  IoArrowForwardOutline,
  IoEyeOutline,
  IoStar,
  IoStarHalf,
  IoStarOutline,
  IoHeartOutline,
  IoGiftOutline,
  IoHelpBuoyOutline,
  IoLogoDropbox,
  IoChevronDown,
  IoClipboardOutline,
  IoNotifications,
  IoFilter,
} from "react-icons/io5";
import {
  MdEmail,
  MdSpaceDashboard,
  MdGroups,
  MdPersonalInjury,
  MdHistory,
  MdCategory,
  MdEdit,
  MdDeleteForever,
} from "react-icons/md";
import {
  FaUserCircle,
  FaTty,
  FaProductHunt,
  FaMoneyBill,
  FaStarHalfAlt,
  FaCalendarAlt,
  FaRegEdit,
  FaSave,
  FaStar,
  FaRegStar,
  FaFacebook,
  FaDiscord,
  FaYoutube,
  FaShieldAlt,
  FaCar,
  FaWifi,
  FaArrowRight,
  FaChevronRight,
  FaBars,
  FaMoon,
  FaQq,
  FaAngleRight,
  FaAngleDown,
  FaNewspaper,
  FaTicketAlt,
  FaPaperPlane,
  FaGithub,
  FaFacebookF,
  FaInstagram,
} from "react-icons/fa";
import {
  AiFillHome,
  AiFillStar,
  AiOutlineStar,
  AiFillEye,
  AiOutlineMenu,
  AiOutlineLogout,
  AiFillGift,
  AiOutlineDown,
  AiFillLike,
  AiOutlineSafety,
} from "react-icons/ai";
import {
  BsFillSuitHeartFill,
  BsReplyFill,
  BsShieldShaded,
  BsFillTelephoneFill,
  BsSunFill,
} from "react-icons/bs";
const icons = {
  // Font Awesome 5
  FaUserCircle,
  FaTty,
  FaAngleDown,
  FaProductHunt,
  FaMoneyBill,
  FaStarHalfAlt,
  FaCalendarAlt,
  FaRegEdit,
  FaSave,
  FaStar,
  FaRegStar,
  FaFacebook,
  FaDiscord,
  FaYoutube,
  FaShieldAlt,
  FaCar,
  FaWifi,
  FaGithub,
  FaFacebookF,
  FaInstagram,
  FaArrowRight,
  FaChevronRight,
  FaBars,
  FaXmark,
  FaAngleRight,
  FaMoon,
  FaQq,
  FaNewspaper,
  FaMoon,
  FaAngleRight,
  FaAngleDown,
  FaTicketAlt,
  FaPaperPlane,
  // Ionicons 5
  IoCartOutline,
  IoLogOutOutline,
  IoReaderOutline,
  IoPersonOutline,
  IoNotificationsOutline,
  IoMoonOutline,
  IoSunnyOutline,
  IoTimeOutline,
  IoBarChartOutline,
  IoPeopleOutline,
  IoCreateOutline,
  IoFootballOutline,
  IoLogoBuffer,
  IoPricetagOutline,
  IoNewspaperOutline,
  IoChatbubblesOutline,
  IoTicketOutline,
  IoReturnUpBackOutline,
  IoPlaySkipBackOutline,
  IoLogInOutline,
  IoPhonePortrait,
  IoHome,
  IoMail,
  IoIosArrowForward,
  IoArrowForwardOutline,
  IoEyeOutline,
  IoStarOutline,
  IoStar,
  IoStarHalf,
  IoHeartOutline,
  IoGiftOutline,
  IoHelpBuoyOutline,
  IoLogoDropbox,
  IoChevronDown,
  IoClipboardOutline,
  IoNotifications,
  IoFilter ,
  // Material Design icons
  MdEmail,
  MdSpaceDashboard,
  MdGroups,
  MdDeleteForever,
  MdCategory,
  MdEdit,
  MdPersonalInjury,
  MdHistory,
  // Ant Design Icons
  AiFillHome,
  AiFillStar,
  AiOutlineStar,
  AiFillEye,
  AiOutlineMenu,
  AiOutlineLogout,
  AiFillGift,
  AiOutlineDown,
  AiOutlineSafety,
  AiFillLike,
  // Bootstrap Icons
  BsFillSuitHeartFill,
  BsReplyFill,
  BsShieldShaded,
  BsCart,
  BsFillTelephoneFill,
  BsSunFill,
  // Lucide
  LuSun,
  LuArrowLeftToLine,
  // Other icon
  BiSolidLogOut,
  RiPhoneFill,
  GoDotFill,
  TiCancel,
  SiBrandfolder,
  FiBox,
};

export default icons;
